package eu.studio742.imago.core.data.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

@Database(
    entities = [
        AssetEntity::class,
        LibraryIdentityEntity::class,
        RemoteKeyEntity::class,
        RecipeEntity::class,
        SavedRecipeEntity::class,
        DerivedAssetEntity::class,
        CompositionProjectEntity::class,
        CompositionTemplateEntity::class,
        BrandKitEntity::class,
        CatalogMonthEntity::class,
        SyncCursorEntity::class,
        LibraryLinkEntity::class,
        ContentHashEntity::class,
        RemoteRecipeEntity::class,
        RecipeConflictEntity::class,
        CandidateRejectionEntity::class,
        AssetLocationEntity::class,
        ArchivedAssetEntity::class,
        StackMemberEntity::class,
        UnifiedStackEntity::class,
    ],
    version = 16,
    exportSchema = true,
)
@ConstructedBy(ImmichRoomDatabaseConstructor::class)
abstract class ImmichRoomDatabase : RoomDatabase() {
    abstract fun libraryIdentityDao(): LibraryIdentityDao
    abstract fun assetDao(): AssetDao
    abstract fun remoteKeyDao(): RemoteKeyDao
    abstract fun recipeDao(): RecipeDao
    abstract fun savedRecipeDao(): SavedRecipeDao
    abstract fun derivedAssetDao(): DerivedAssetDao
    abstract fun compositionProjectDao(): CompositionProjectDao
    abstract fun compositionTemplateDao(): CompositionTemplateDao
    abstract fun brandKitDao(): BrandKitDao
    abstract fun catalogMonthDao(): CatalogMonthDao
    abstract fun contentHashDao(): ContentHashDao
    abstract fun libraryLinkDao(): LibraryLinkDao
    abstract fun syncCursorDao(): SyncCursorDao
    abstract fun remoteRecipeDao(): RemoteRecipeDao
    abstract fun recipeConflictDao(): RecipeConflictDao
    abstract fun candidateRejectionDao(): CandidateRejectionDao
    abstract fun assetLocationDao(): AssetLocationDao
    abstract fun archivedAssetDao(): ArchivedAssetDao
    abstract fun stackMemberDao(): StackMemberDao
    abstract fun unifiedStackDao(): UnifiedStackDao
}

/** Generated by Room for each platform. */
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpect")
expect object ImmichRoomDatabaseConstructor : RoomDatabaseConstructor<ImmichRoomDatabase> {
    override fun initialize(): ImmichRoomDatabase
}
